public record BetaWeeklyRollup(
    DateOnly WeekStartDate,
    int CohortSize,
    int WeeklyActiveUsers,
    double D7RetentionRate,
    double RelevancePositiveRatio,
    double AlertClickThroughRate,
    double SourceClickRate,
    double ExplanationPolicyViolationRate,
    string KpiHealth,
    string Recommendation,
    double FalseRelevanceRate,
    double DuplicateAlertRate,
    double MissingSourceRate,
    IReadOnlyList<string> TopFeedbackThemes,
    string RuleVersion,
    string? Notes);
